# logs are stored in subdirectories which match the service folder name
filebeat.modules:
  - module: apache2
    access:
      enabled: true
      var.paths:
        - /usr/share/logs/adaptation/access_log*.log
        - /usr/share/logs/adaptation/application*.log

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 3

setup.kibana:
  host: "kibana:5601"

setup.dashboards.enabled: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
