version: "3.3"
services:
  adaptation:
    build:
      context: adaptation
      dockerfile: Dockerfile
    depends_on: ["adaptation_mongo"]
    ports: ["27182:27182"]
    volumes:
      - adaptation_files:/usr/src/app/adaptation_files
      - adaptation_logs:/var/log/adaptation
  adaptation_mongo:
    command: ["mongod", "--port", "27020", "--smallfiles"]
    image: mongo:3.2
    ports: ["27020:27020"]
    volumes: ["adaptation_mongo_data:/data/db"]
  adaptation_runtime:
    build:
      context: adaptation-runtime
      dockerfile: Dockerfile
    command: ["--spring.profiles.active=production"]
    depends_on: ["rabbitmq", "adaptation", "tyk_gateway"]
    restart: always
    volumes:
      - adaptation_files:/usr/src/app/adaptation_files
  plan:
    build:
      context: plan
      dockerfile: Dockerfile
    command: ["--spring.profiles.active=production"]
    depends_on: ["plan_mongo"]
    ports: ["27183:27183"]
    restart: always
    volumes: ["plan_logs:/var/log/plan"]
  plan_mongo:
    command: ["mongod", "--port", "27018", "--smallfiles"]
    image: mongo:3.2
    ports: ["27018:27018"]
    volumes: ["plan_mongo_data:/data/db"]
  simulation:
    build:
      context: simulation
      dockerfile: Dockerfile
    command: ["--spring.profiles.active=production"]
    depends_on: ["rabbitmq"]
    ports: ["27185:27185"]
    restart: always
    volumes: ["simulation_logs:/var/log/simulation"]
  sequencing:
    build:
      context: sequencing
      dockerfile: Dockerfile
    command: ["npm", "run", "start:dev"]
    depends_on: ["sequencing_mongo"]
    ports: ["27186:27186"]
    restart: always
    volumes: ["sequencing_logs:/var/log/sequencing"]
  sequencing_mongo:
    command: ["mongod", "--port", "27019"]
    image: mongo:3.2
    ports: ["27019:27019"]
    volumes: ["sequencing_mongo_data:/data/db"]

  rabbitmq:
    image: rabbitmq:3
    hostname: rabbitmq
    ports: ["5672:5672"]
    volumes: ["rabbitmq_data:/var/lib/rabbitmq/mnesia/rabbit@rabbitmq"]

  tyk_gateway:
    image: tykio/tyk-gateway:latest
    ports: ["8081:8081"]
    environment:
      TYKLISTENPORT: 8081
    depends_on:
      - tyk_redis
    restart: always
    volumes:
      - ./tyk_gateway/tyk_gateway_local.conf:/opt/tyk-gateway/tyk.conf
      - ./tyk_gateway/apps:/opt/tyk-gateway/apps
  tyk_redis:
    image: redis
    ports: ["6379:6379"]
    volumes:
      - tyk_redis_data:/data

volumes:
  adaptation_files:
  adaptation_logs:
  adaptation_mongo:
  plan_logs:
  plan_mongo_data:
  rabbitmq_data:
  tyk_redis_data:
  simulation_logs:
  sequencing_logs:
  sequencing_mongo_data:
