version: "3.3"
services:
  adaptation:
    image: "${DOCKER_URL}/adaptation:${DOCKER_TAG}"
    ports: ["27182:27182"]
    depends_on: ["adaptation_mongo"]
    volumes:
      - adaptation_files:/usr/src/app/adaptation_files
      - adaptation_logs:/var/log/adaptation
  adaptation_mongo:
    command: ["mongod", "--port", "27020", "--smallfiles"]
    image: mongo:3.2
    ports: ["27020:27020"]
    volumes: ["adaptation_mongo_data:/data/db"]
  nest:
    image: "${DOCKER_URL}/nest:${DOCKER_TAG}"
    ports: ["8080:80"]
  plan:
    image: "${DOCKER_URL}/plan:${DOCKER_TAG}"
    command: ["--spring.profiles.active=production"]
    depends_on: ["plan_mongo"]
    ports: ["27183:27183"]
    restart: always
    volumes: ["plan_logs:/var/log/plan"]
  plan_mongo:
    command: ["mongod", "--port", "27018", "--smallfiles"]
    image: mongo:3.2
    ports: ["27018:27018"]
    volumes: ["plan_mongo_data:/data/db"]

volumes:
  adaptation_files:
  adaptation_logs:
  adaptation_mongo:
  plan_logs:
  plan_mongo_data:
