version: "3.3"
services:
  adaptation:
    image: cae-artifactory.jpl.nasa.gov:16001/gov/nasa/jpl/ammos/mpsa/aerie/adaptation
    ports: ["27182:27182"]
    volumes:
      - adaptation_files:/usr/src/app/adaptation_files
      - adaptation_logs:/var/log/adaptation
  nest:
    image: cae-artifactory.jpl.nasa.gov:16001/gov/nasa/jpl/ammos/mpsa/aerie/nest
    ports: ["8080:80"]
  plan:
    image: cae-artifactory.jpl.nasa.gov:16001/gov/nasa/jpl/ammos/mpsa/aerie/plan
    command: ["--spring.profiles.active=production"]
    depends_on: ["plan_mongo"]
    ports: ["27183:27183"]
    restart: always
    volumes: ["plan_logs:/var/log/plan"]
  plan_mongo:
    command: ["mongod", "--port", "27018", "--smallfiles"]
    image: mongo:3.2
    ports: ["27018:27018"]
    volumes: ["plan_mongo_data:/data/db"]
  sequencing:
    image: cae-artifactory.jpl.nasa.gov:16001/gov/nasa/jpl/ammos/mpsa/aerie/sequencing
    command: ["npm", "run", "start:prod"]
    depends_on: ["sequencing_mongo"]
    ports: ["27186:27186"]
    restart: always
    volumes: ["sequencing_logs:/var/log/sequencing"]
  sequencing_mongo:
    command: ["mongod", "--port", "27019"]
    image: mongo:3.2
    ports: ["27019:27019"]
    volumes: ["sequencing_mongo_data:/data/db"]

volumes:
  adaptation_files:
  adaptation_logs:
  plan_logs:
  plan_mongo_data:
  sequencing_logs:
  sequencing_mongo_data:
