swagger: "2.0"
info:
  version: 1.0.0
  title: .
  description: Normalizes command dictionaries
basePath: /api
tags:
  - name: Specification
    description: The swagger API specification

consumes:
  - application/xml
produces:
  - application/json

definitions:
  ExampleBody:
    type: object
    title: example
    required:
      - name
    properties:
      name:
        type: string
        example: no_stress

paths:
  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification

  /europa:
    post:
      tags:
        - Europa
      description: Accepts a Europa Command Dictionary (XML) and returns a MPS Command Dictionary (JSON)
      parameters:
        - name: example
          in: body
          description: an example
          required: true
          schema:
            $ref: "#/definitions/ExampleBody"
      responses:
        200:
          description: Return a MPS Command Dictionary (JSON)
        400:
          description: An error occured while parsing the Europa Command Dictionary. Please check if it's in the correct format.
