version: '3.3'
services:
  tyk_dashboard:
    image: tykio/tyk-dashboard:latest
    ports:
    - "3000:3000"
    - "5000:5000"
    depends_on:
    - tyk_redis
    - tyk_mongo
    restart: always
  tyk_gateway:
    image: tykio/tyk-gateway:latest
    ports:
    - "8081:8080"
    depends_on:
    - tyk_redis
    restart: always
  tyk_pump:
    image: tykio/tyk-pump-docker-pub:latest
    depends_on:
    - tyk_redis
    - tyk_mongo
    - tyk_gateway
    restart: always
  tyk_redis:
    image: redis
    ports:
    - "6379:6379"
    volumes:
    - tyk_redis_data:/data
  tyk_mongo:
    image: mongo:3.2
    command: ["mongod", "--smallfiles"]
    ports:
    - "27017:27017"
    volumes:
    - tyk_mongo_data:/data/db

volumes:
  tyk_mongo_data:
  tyk_redis_data:
