version: '3.3'
services:
  tyk_dashboard:
    volumes:
      - ../tyk_dashboard/tyk_dashboard.conf:/opt/tyk-dashboard/tyk_analytics.conf
  tyk_gateway:
    volumes:
    - ../tyk_gateway/tyk_gateway.conf:/opt/tyk-gateway/tyk.conf
    - ../tyk_gateway/apps:/opt/tyk-gateway/apps
  tyk_pump:
    volumes:
    - ../tyk_pump/tyk_pump.conf:/opt/tyk-pump/pump.conf
