version: "3.7"
services:
  aerie_gateway:
    container_name: aerie_gateway
    depends_on: ["postgres"]
    environment:
      AUTH_TYPE: cam
      AUTH_URL: https://atb-ocio-12b.jpl.nasa.gov:8443/cam-api
      GQL_API_URL: http://localhost:8080/v1/graphql
      PORT: 9000
      POSTGRES_AERIE_MERLIN_DB: aerie_merlin
      POSTGRES_AERIE_SCHEDULER_DB: aerie_scheduler
      POSTGRES_AERIE_UI_DB: aerie_ui
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: aerie
      POSTGRES_PORT: 5432
      POSTGRES_USER: aerie
    image: "ghcr.io/nasa-ammos/aerie-gateway:latest"
    ports: ["9000:9000"]
    restart: always
    volumes:
      - aerie_file_store:/app/files
  aerie_merlin:
    container_name: aerie_merlin
    depends_on: ["postgres"]
    environment:
      MERLIN_DB: "aerie_merlin"
      MERLIN_DB_PASSWORD: "aerie"
      MERLIN_DB_PORT: 5432
      MERLIN_DB_SERVER: "postgres"
      MERLIN_DB_USER: "aerie"
      MERLIN_LOCAL_STORE: /usr/src/app/merlin_file_store
      MERLIN_LOGGING: "true"
      MERLIN_PORT: 27183
    image: "ghcr.io/nasa-ammos/aerie-merlin:latest"
    ports: ["27183:27183"]
    restart: always
    volumes:
      - aerie_file_store:/usr/src/app/merlin_file_store
  aerie_scheduler:
    container_name: aerie_scheduler
    depends_on: ["aerie_merlin", "postgres"]
    environment:
      MERLIN_GRAPHQL_URL: http://hasura:8080/v1/graphql
      MERLIN_LOCAL_STORE: /usr/src/app/merlin_file_store
      SCHEDULER_DB: "aerie_scheduler"
      SCHEDULER_DB_PASSWORD: "aerie"
      SCHEDULER_DB_PORT: 5432
      SCHEDULER_DB_SERVER: "postgres"
      SCHEDULER_DB_USER: "aerie"
      SCHEDULER_LOCAL_STORE: /usr/src/app/scheduler_file_store
      SCHEDULER_LOGGING: "true"
      SCHEDULER_OUTPUT_MODE: UpdateInputPlanWithNewActivities
      SCHEDULER_PORT: 27193
      SCHEDULER_RULES_JAR: /usr/src/app/merlin_file_store/scheduler_rules.jar
    image: "ghcr.io/nasa-ammos/aerie-scheduler:latest"
    ports: ["27193:27193"]
    restart: always
    volumes:
      - aerie_file_store:/usr/src/app/merlin_file_store
  aerie_ui:
    container_name: aerie_ui
    depends_on: ["postgres"]
    environment:
      AUTH_TYPE: cam
      GATEWAY_CLIENT_URL: http://localhost:9000
      GATEWAY_SERVER_URL: http://aerie_gateway:9000
      HASURA_CLIENT_URL: http://localhost:8080/v1/graphql
      HASURA_SERVER_URL: http://hasura:8080/v1/graphql
      SCHEDULER_CLIENT_URL: http://localhost:27193
      SCHEDULER_SERVER_URL: http://scheduler:27193
    image: "ghcr.io/nasa-ammos/aerie-ui:latest"
    ports: ["80:80"]
    restart: always
  hasura:
    container_name: hasura
    depends_on: ["postgres"]
    environment:
      AERIE_MERLIN_DATABASE_URL: postgres://aerie:aerie@postgres:5432/aerie_merlin
      AERIE_SCHEDULER_DATABASE_URL: postgres://aerie:aerie@postgres:5432/aerie_scheduler
      AERIE_UI_DATABASE_URL: postgres://aerie:aerie@postgres:5432/aerie_ui
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://aerie:aerie@postgres:5432/aerie_hasura
      HASURA_GRAPHQL_METADATA_DIR: /hasura-metadata
    image: "hasura/graphql-engine:v2.2.0.cli-migrations-v3"
    ports: ["8080:8080"]
    restart: always
    volumes:
      - ./hasura/metadata:/hasura-metadata
  postgres:
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    image: postgres:14.1
    ports: ["5432:5432"]
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init-db:/docker-entrypoint-initdb.d

volumes:
  aerie_file_store:
  mission_file_store:
  postgres_data:
