[package]
name = "plan"
version = "0.1.0"
authors = ["Dustin Boston <dustin.m.boston@jpl.nasa.gov>"]

[dependencies]
rocket = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

[dependencies.rocket_contrib]
version = "0.4"
default-features = false
features = ["json", "mongodb_pool"]