name: ci

on:
  push:
    branches:
      - develop
    tags:
      - v*
  pull_request:
    branches:
      - develop

env:
  REGISTRY: ghcr.io

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "17"
      - uses: gradle/wrapper-validation-action@v1
      - name: Build Classes
        run: ./gradlew classes
      - name: Test
        run: ./gradlew test
      - name: Assemble
        run: ./gradlew assemble
      - name: Login to the Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
      # Build aerie-merlin Docker artifacts.
      - name: Extract metadata (tags, labels) for aerie-merlin Docker image
        if: github.event_name != 'pull_request'
        id: aerieMerlin
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/aerie-merlin
      - name: Build and push aerie-merlin Docker image
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v2
        with:
          context: ./merlin-server
          push: true
          tags: ${{ steps.aerieMerlin.outputs.tags }}
          labels: ${{ steps.aerieMerlin.outputs.labels }}
      # Build aerie-scheduler Docker artifacts.
      - name: Extract metadata (tags, labels) for aerie-scheduler Docker image
        if: github.event_name != 'pull_request'
        id: aerieScheduler
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/aerie-scheduler
      - name: Build and push aerie-scheduler Docker image
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v2
        with:
          context: ./scheduler-server
          push: true
          tags: ${{ steps.aerieScheduler.outputs.tags }}
          labels: ${{ steps.aerieScheduler.outputs.labels }}
