name: Deploy to GitHub Pages

on:
  push:
    branches:
      - develop
    tags:
      - v*
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 19
      - uses: gradle/gradle-build-action@v2
      - name: Build EDSL API Docs
        run: ./gradlew publishDocs
      - name: Create Pages Build Directory
        run: mkdir build
      - name: Copy EDSL API Docs to Build Directory
        run: |
          cp -a ./merlin-server/constraints-dsl-compiler/build/docs ./build/constraints-edsl-api
          cp -a ./scheduler-worker/scheduling-dsl-compiler/build/docs ./build/scheduling-edsl-api
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: build/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
