name: publish

on:
  push:
    branches:
      - develop
    tags:
      - v*

env:
  REGISTRY: ghcr.io
  IS_RELEASE: ${{ startsWith(github.ref, 'refs/tags/v') }}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "19"
      - uses: gradle/wrapper-validation-action@v1
      - uses: gradle/gradle-build-action@v2
      - name: Build Classes
        run: ./gradlew classes
      - name: Test
        run: ./gradlew test
      - name: Publish Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: JUnit Test Report
          path: '**/build/test-results/test/TEST-*.xml'
          reporter: java-junit
      - name: Assemble
        run: ./gradlew assemble
      - name: Login to the Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
      # Build, scan, and push aerie-merlin Docker artifacts.
      - name: Extract metadata (tags, labels) for aerie-merlin Docker image
        id: aerieMerlin
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/nasa-ammos/aerie-merlin
      - name: Build aerie-merlin Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./merlin-server
          load: true
          tags: ${{ env.REGISTRY }}/nasa-ammos/aerie-merlin:${{ github.sha }}
      - name: Scan aerie-merlin Docker image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/nasa-ammos/aerie-merlin:${{ github.sha }}
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          severity: 'CRITICAL'
      - name: Push aerie-merlin Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./merlin-server
          push: true
          tags: ${{ steps.aerieMerlin.outputs.tags }}
          labels: ${{ steps.aerieMerlin.outputs.labels }}
      # Build, scan, and push aerie-merlin-worker Docker artifacts.
      - name: Extract metadata (tags, labels) for aerie-merlin-worker Docker image
        id: aerieMerlinWorker
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/nasa-ammos/aerie-merlin-worker
      - name: Build aerie-merlin-worker Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./merlin-worker
          load: true
          tags: ${{ env.REGISTRY }}/nasa-ammos/aerie-merlin-worker:${{ github.sha }}
      - name: Scan aerie-merlin-worker Docker image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/nasa-ammos/aerie-merlin-worker:${{ github.sha }}
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          severity: 'CRITICAL'
      - name: Push aerie-merlin-worker Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./merlin-worker
          push: true
          tags: ${{ steps.aerieMerlinWorker.outputs.tags }}
          labels: ${{ steps.aerieMerlinWorker.outputs.labels }}
      # Build, scan, and push aerie-scheduler-worker Docker artifacts.
      - name: Extract metadata (tags, labels) for aerie-scheduler-worker Docker image
        id: aerieSchedulerWorker
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/nasa-ammos/aerie-scheduler-worker
      - name: Build aerie-scheduler-worker Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./scheduler-worker
          load: true
          tags: ${{ env.REGISTRY }}/nasa-ammos/aerie-scheduler-worker:${{ github.sha }}
      - name: Scan aerie-scheduler-worker Docker image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/nasa-ammos/aerie-scheduler-worker:${{ github.sha }}
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          severity: 'CRITICAL'
      - name: Push aerie-scheduler-worker Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./scheduler-worker
          push: true
          tags: ${{ steps.aerieSchedulerWorker.outputs.tags }}
          labels: ${{ steps.aerieSchedulerWorker.outputs.labels }}
      # Build, scan, and push aerie-scheduler Docker artifacts.
      - name: Extract metadata (tags, labels) for aerie-scheduler Docker image
        id: aerieScheduler
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/nasa-ammos/aerie-scheduler
      - name: Build aerie-scheduler Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./scheduler-server
          load: true
          tags: ${{ env.REGISTRY }}/nasa-ammos/aerie-scheduler:${{ github.sha }}
      - name: Scan aerie-scheduler Docker image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/nasa-ammos/aerie-scheduler:${{ github.sha }}
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          severity: 'CRITICAL'
      - name: Push aerie-scheduler Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./scheduler-server
          push: true
          tags: ${{ steps.aerieScheduler.outputs.tags }}
          labels: ${{ steps.aerieScheduler.outputs.labels }}
      # Build, scan, and push aerie-commanding Docker artifacts.
      - name: Extract metadata (tags, labels) for aerie-commanding Docker image
        id: aerieCommanding
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/nasa-ammos/aerie-commanding
      - name: Build aerie-commanding Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./command-expansion-server
          load: true
          tags: ${{ env.REGISTRY }}/nasa-ammos/aerie-commanding:${{ github.sha }}
      - name: Scan aerie-commanding Docker image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/nasa-ammos/aerie-commanding:${{ github.sha }}
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          severity: 'CRITICAL'
      - name: Push aerie-commanding Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./command-expansion-server
          push: true
          tags: ${{ steps.aerieCommanding.outputs.tags }}
          labels: ${{ steps.aerieCommanding.outputs.labels }}
      # Publish via Gradle.
      - name: Publish Package
        run: ./gradlew publish -Pversion.isRelease=$IS_RELEASE
        env:
          GITHUB_TOKEN: ${{ github.token }}
      # Publish deployment via action artifact uploader.
      - name: Create deployment archive
        run: ./gradlew archiveDeployment
      - name: Publish deployment
        uses: actions/upload-artifact@v2
        with:
          name: Deployment
          path: deployment.tar
