name: test

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
    tags:
      - v*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Setup Postgres Client (psql)
        run: sudo apt-get install --yes postgresql-client
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build Classes
        run: ./gradlew classes
      - name: Assemble
        run: ./gradlew assemble
      - name: Validate Docker Configurations
        # `docker-compose` and `docker compose` have different "leniencies"
        run: |
          find . -name docker-compose\*.yml | while read -r file; do \
            echo "$file"; \
            docker-compose -f "$file" config -q && \
            docker compose -f "$file" config -q; \
          done
      - name: Start Services
        run: |
          docker compose -f ./e2e-tests/docker-compose-test.yml up -d --build
          docker images
          docker ps -a
      - name: Sleep for 30 Seconds
        run: sleep 30s
        shell: bash
      - name: Run Unit Tests
        run: ./gradlew test
      - name: Run E2E Tests
        run: ./gradlew e2eTest
      - name: Report JUnit Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: ☕ JUnit Results
          path: "**/build/test-results/**/TEST-*.xml"
          reporter: java-junit
      - name: Upload JUnit Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ☕ JUnit Results
          path: "**/build/test-results/**/TEST-*.xml"
      - name: Upload Playwright Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: 🎭 Playwright Results
          path: ./e2e-tests/test-results
      - name: Print Logs for Services
        run: docker compose -f ./e2e-tests/docker-compose-test.yml logs -t
      - name: Stop Services
        run: |
          docker ps -a
          docker compose -f ./e2e-tests/docker-compose-test.yml down
          docker ps -a
      - name: Prune Volumes
        run: docker volume prune --force
